# Generated by Django 5.0.2 on 2024-02-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='adress',
            new_name='address',
        ),
    ]
