# Generated by Django 5.0.2 on 2024-04-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRatings',
            new_name='ProductRating',
        ),
    ]
